name: artifact_removal
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.44.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - mpi=1.0
  - mpi4py=3.1.5
  - mpich=4.1.2
  - ncurses=6.4
  - openssl=3.1.4
  - pip=23.3.1
  - python=3.9.18
  - python_abi=3.9
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - wheel=0.41.3
  - xz=5.2.6
  - pip:
      - argparse==1.4.0
      - batchgenerators==0.25
      - blobfile==2.1.1
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.44.0
      - future==0.18.3
      - idna==3.4
      - imageio==2.32.0
      - imgaug==0.4.0
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - linecache2==1.0.0
      - lpips==0.1.4
      - lxml==4.9.3
      - matplotlib==3.8.1
      - networkx==3.2.1
      - nibabel==5.1.0
      - numpy==1.26.1
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.3
      - pillow==10.0.1
      - protobuf==4.25.2
      - pycryptodomex==3.19.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch-fid==0.3.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - shapely==2.0.2
      - simpleitk==2.3.1
      - six==1.16.0
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchsummary==1.5.1
      - torchvision==0.14.1+cu117
      - tornado==6.3.3
      - tqdm==4.66.1
      - traceback2==1.4.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - unittest2==1.1.0
      - urllib3==2.0.7
      - visdom==0.2.4
      - websocket-client==1.6.4
      - zipp==3.17.0
